# Generated by Django 3.2.6 on 2022-12-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_daily_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_usage',
            name='time_of_the_day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
