# Generated by Django 3.2.6 on 2022-12-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_daily_usage_time_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
